### PR TITLE
Add 'Async' suffix to async methods

### LINKED ISSUE #141: Standardize on `Async` suffix in methods
Currently, we have a bit of a mess in terms of this convention. It would be nice to standardize. I personally vote to make all async methods end with the corresponding suffix, as is customary in C#.

Example:

- Has `...Async`:

https://github.com/passwordless/passwordless-server/blob/8eac1bbc5eabdecef791a3720ed83be80e884865/src/AdminConsole/Services/ISharedBillingService.cs#L7-L21

- Does not have `...Async`:

https://github.com/passwordless/passwordless-server/blob/e63d0293660c69e2ef91d4224685c35ad00cd5b5/src/AdminConsole/Services/TimedHostedService.cs#L37-L85

### PR DESCRIPTION
**Pull request by pooya1380m**
as result of #141 I added 'Async' suffix to async methods

Closes #141

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Thank you @pooya1380m.

Could you please also add a rule in `editorconfig` to have `dotnet format` error on these issues automatically? I think this provides a bit more context: https://stackoverflow.com/a/53973220

**Comment by pooya1380m** [comment]
> Thank you @pooya1380m.
> 
> Could you please also add a rule in `editorconfig` to have `dotnet format` error on these issues automatically? I think this provides a bit more context: https://stackoverflow.com/a/53973220

just added

**Review by Tyrrrz — APPROVED** [review]

**Comment by Tyrrrz** [comment]
Internal note: workflow fails to report test results due to permission elevation issues on external PRs, as explained [here](https://bitwarden.com/blog/how-to-set-up-a-testing-workflow-for-a-net-library/#reporting-test-results).

**Comment by pooya1380m** [comment]
> [here](https://bitwarden.com/blog/how-to-set-up-a-testing-workflow-for-a-net-library/#reporting-test-results)

@Tyrrrz I have some problem with that
1. Im confused which yaml should I use 
2. testcontaner use adm64 for test and Im using Arm so tests fails

**Comment by Tyrrrz** [comment]
> > [here](https://bitwarden.com/blog/how-to-set-up-a-testing-workflow-for-a-net-library/#reporting-test-results)
> 
> @Tyrrrz I have some problem with that
> 
> 1. Im confused which yaml should I use
> 2. testcontaner use adm64 for test and Im using Arm so tests fails

Sorry for the confusion @pooya1380m. That comment was an internal note explaining to the team why the test reporting stage failed. I was not trying to prompt you to do anything 🙂

**Comment by pooya1380m** [comment]
> > > [here](https://bitwarden.com/blog/how-to-set-up-a-testing-workflow-for-a-net-library/#reporting-test-results)
> > 
> > 
> > @Tyrrrz I have some problem with that
> > 
> > 1. Im confused which yaml should I use
> > 2. testcontaner use adm64 for test and Im using Arm so tests fails
> 
> Sorry for the confusion @pooya1380m. That comment was an internal note explaining to the team why the test reporting stage failed. I was not trying to prompt you to do anything 🙂

**Comment by pooya1380m** [comment]
any flur

> > > > [here](https://bitwarden.com/blog/how-to-set-up-a-testing-workflow-for-a-net-library/#reporting-test-results)
> > > 
> > > 
> > > @Tyrrrz I have some problem with that
> > > 
> > > 1. Im confused which yaml should I use
> > > 2. testcontaner use adm64 for test and Im using Arm so tests fails
> > 
> > 
> > Sorry for the confusion @pooya1380m. That comment was an internal note explaining to the team why the test reporting stage failed. I was not trying to prompt you to do anything 🙂
@Tyrrrz 
I get that thanks
but do you have any solution for testcontainer amd64 containers on arm64 ?

**Comment by Tyrrrz** [comment]
Which image/container are you having issues with? I assume it's the MSSQL server?

**Review by Tyrrrz — APPROVED** [review]

**Comment by pooya1380m** [comment]
> Which image/container are you having issues with? I assume it's the MSSQL server?

@Tyrrrz all containers that test container creates

**Comment by Tyrrrz** [comment]
You should be able to run it with emulation, but otherwise this is the issue tracking this https://github.com/microsoft/mssql-docker/issues/802

**Pull request merged**
