### PR TITLE
PAS64: Limit users to 10k on free plan.

### PR DESCRIPTION
**Pull request by jonashendrickx**
Goes with https://github.com/passwordless/docs/pull/44

### CODE REVIEW

**Comment by jonashendrickx** [comment]
Scripts have not been generated yet for the in-house migration.

**Comment by jonashendrickx** [comment]
image

We only needed to show the error in the playground. But error is returned by the API when a new user (with new user id) tries to register.

**Comment by jonashendrickx** [comment]
Configuration is set in appsettings.json. No extra configuration required on server.

**Comment by abergs** [comment]
@jonashendrickx Let's have a call tomorrow and walk through some of these changes!

**Pull request closed without merging**
